### ISSUE TITLE
Заменяет содержимое тега <style>

### ISSUE THREAD

**Issue by woodingo** [nikbelikov/word-wrap-checker#1]
Тестировано на AngularJS приложении, выдает вот такую картину. Есть возможность пофиксить?
```
<style md-theme-style="">
    The longest non-technical word in major dictionaries is floccinaucinihilipilification at 29 letters.
</style>
```

**Comment by nikbelikov** [comment]
@woodingo Спасибо за обращение. Постараюсь сделать.

**Comment by nikbelikov** [comment]
@woodingo 
Баг исправлен.
Новая версия доступна в сторе.
